project:
  type: website
  pre-render:
    - ./pre-render.py
  post-render:
    - ./post-render.py
  render:
    - "Index.qmd"
    - "Resume.qmd"
    - "Publications.qmd"

website:
  title: "Elias Del Pozo"
  navbar:
    left:
      - href: Index.qmd
        text: "Home"
      - href: Resume.qmd
        text: "CV"
      - href: Publications.qmd
        text: "Publications"
  page-footer:
    border: true
    background: dark
    center: 
      - text: "<b>Download presentation</b>"
        href: /Index.pdf
      - text: "<b>Download CV</b>"
        href: /Resume.pdf
      - text: "<b>Download Publications</b>"
        href: /Publications.pdf

format-links: false
format:
  html:
    theme: minty
    css: styles.css
    link-external-newwindow: true
    canonical-url: true
  pdf: default

resources:
  - CNAME
