# Elías Del Pozo
Master of Computer Science and Technology
| [edelpozo@inf.uc3m.es](mailto:edelpozo@inf.uc3m.es)
| [+34 916246260](tel:+34916246260)
| [LinkedIn.com](https://www.linkedin.com/in/edelpozop/)


## Work Experience

::: {.justify}

TODO


## Education

### Master in Computer Science and Technology
*University Carlos III of Madrid*  
*21/07/2020 - 9,9/10*

Thesis title (es): Desarrollo de un simulador genérico para infraestructuras Edge y Fog Computing.
Thesis title (en): Development of a generic simulator for Edge and Fog Computing infrastructures.

### Bachelor degree in Computer Science
*University Carlos III of Madrid*  
*03/07/2019 - 9,6/10*

Thesis title (es): Diseño y Desarrollo de un Sistema de Ficheros Distribuido y Paralelo basado en Apache Cassandra.
Thesis title (en): Design and Development of a Distributed and Parallel File System based on Apache Cassandra.


## Projects

### Nuevas técnicas escalables de E/S para cargas de trabajo híbridas de HPC e intensivas en datos (SCIOT).

Participation: Member of the working group

### Integrated development environment for teaching and research on RISC-V processors.

Participation: Member of the working group

### Nuevas técnicas escalables de E/S para cargas de trabajo híbridas de HPC e intensivas en datos (SCIOT).

Participation: Member of the working group

### Expand - Sistema de almacenamiento de altas prestaciones para entornos HPC y Big Data.

Participation: Member of the working group

### Towards Unification of HPC and Big Data Paradigms (BIGHPC). Ministerio de Economía y Competitividad

Participation: Member of the working group

### ConvergenciA Big dAta-Hpc: de Los sensores a las Aplicaciones (CABAHLA). Comunidad Autónoma de Madrid

Participation: Member of the working group

### New Data Intensive Computing Methods for High-End and Edge Computing Platforms (DECIDE).

Participation: Member of the working group

### Expansion of program functionalities: Energy supply analysis and calculation system (SYCE).

Participation: Member of the working group

### Program Maintenance: Energy Supply Calculation and Analysis System (SYCE). ADIF.

Participation: Member of the working group


## Languages

- English: Advanced
- Spanish: Native

## Skills

- Databases: SQL, Apache Cassandra. 
- Development Environments: Visual Studio, CLion.
- Experience in: File systems, Distributed Systems, HPC, Machine Learning, SimGrid Simulation Environment.
- Machine Learning: PyTorch
- Programming languages: C, Python, HTML, Java, Javascript, C++, C\#.
- Text Editing: MS Office, LaTeX.

## Others

- International research stay at the Inria center of the University of Rennes, in the KerData research group, Rennes, France (2025). Three-month research stay
- Driving License - B
- Cambridge English Level 1 Certificate in ESOL International (First), FCE1 2015, Council of Europe Level B2.
- Journal Paper Reviewer
-- ACM Computing Surveys (CSUR), 2025. [IF: 23.8, Q1]
-- IEEE Transactions on Parallel and Distributed Systems (TPDS), 2025. [IF: 5.6, Q1]
  
## Awards, Grants & Honors

- Call for financial aids of the Doctoral School 2025. Modality 2: Financial aids to fund expenses for short research stays outside of Spain. URL: https://www.uc3m.es/phdprogram/call-financial-aids-doctoral-school

- Grants for predoctoral contracts for the training of PhDs 2020. Grants for pre-doctoral contracts for the formation of doctors contemplated in the State Training Subprogram, of the State Program for the Promotion of Talent and its Employability, within the framework of the State Plan for Scientific and Technical Research and Innovation 2017-2020, on a competitive basis and applying the principles of publicity and objectivity. URL: https://www.aei.gob.es/convocatorias/buscador-convocatorias/ayudas-contratos-predoctorales-formacion-doctoresas-2020

- Complete Aid to the Master's Study. University Carlos III of Madrid, 2019-2021. URL: https://www.uc3m.es/postgrado/ayudas 

- MECD Grant. Spanish Ministry of Education, 2016-2019. URL: http://www.educacionyfp.gob.es/servicios-al-ciudadano/catalogo/estudiantes/becas-ayudas/para-estudiar/universidad/grado/becas-generales-universitarias.html 


## Interests

- Technology
- Videogames

:::